
spring:
  application:
    name: kotlin-crud

  sql:
    init:
      platform: mysql

  datasource:
    username: kotlin
    password: kotlin
    url: jdbc:mysql://localhost:3306/kotlin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: admin
      password: 1234

